package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.XxsshrDisContingentLinesEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 13 20:56:11 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxsshrDisContingentLinesVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXSSHRDISCONTINGENTLINESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DisContingentId,
        DisFormId,
        ContiRelationshipType,
        ContiFullName,
        ContiProportion,
        ContiPrimaryContactFlag,
        ContiSecondaryContactFlag,
        ContiComments,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Reference1,
        ContiMobileNo,
        ContiMobileNo1,
        ContiResiAddress,
        ContiEmailAddress,
        ContiDob,
        ContiBeneFlag,
        Relationship_ROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DISCONTINGENTID = AttributesEnum.DisContingentId.index();
    public static final int DISFORMID = AttributesEnum.DisFormId.index();
    public static final int CONTIRELATIONSHIPTYPE = AttributesEnum.ContiRelationshipType.index();
    public static final int CONTIFULLNAME = AttributesEnum.ContiFullName.index();
    public static final int CONTIPROPORTION = AttributesEnum.ContiProportion.index();
    public static final int CONTIPRIMARYCONTACTFLAG = AttributesEnum.ContiPrimaryContactFlag.index();
    public static final int CONTISECONDARYCONTACTFLAG = AttributesEnum.ContiSecondaryContactFlag.index();
    public static final int CONTICOMMENTS = AttributesEnum.ContiComments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int REFERENCE1 = AttributesEnum.Reference1.index();
    public static final int CONTIMOBILENO = AttributesEnum.ContiMobileNo.index();
    public static final int CONTIMOBILENO1 = AttributesEnum.ContiMobileNo1.index();
    public static final int CONTIRESIADDRESS = AttributesEnum.ContiResiAddress.index();
    public static final int CONTIEMAILADDRESS = AttributesEnum.ContiEmailAddress.index();
    public static final int CONTIDOB = AttributesEnum.ContiDob.index();
    public static final int CONTIBENEFLAG = AttributesEnum.ContiBeneFlag.index();
    public static final int RELATIONSHIP_ROVO = AttributesEnum.Relationship_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxsshrDisContingentLinesVORowImpl() {
    }

    /**
     * Gets XxsshrDisContingentLinesEO entity object.
     * @return the XxsshrDisContingentLinesEO
     */
    public XxsshrDisContingentLinesEOImpl getXxsshrDisContingentLinesEO() {
        return (XxsshrDisContingentLinesEOImpl) getEntity(ENTITY_XXSSHRDISCONTINGENTLINESEO);
    }

    /**
     * Gets the attribute value for DIS_CONTINGENT_ID using the alias name DisContingentId.
     * @return the DIS_CONTINGENT_ID
     */
    public BigDecimal getDisContingentId() {
        return (BigDecimal) getAttributeInternal(DISCONTINGENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_CONTINGENT_ID using the alias name DisContingentId.
     * @param value value to set the DIS_CONTINGENT_ID
     */
    public void setDisContingentId(BigDecimal value) {
        setAttributeInternal(DISCONTINGENTID, value);
    }

    /**
     * Gets the attribute value for DIS_FORM_ID using the alias name DisFormId.
     * @return the DIS_FORM_ID
     */
    public BigDecimal getDisFormId() {
        return (BigDecimal) getAttributeInternal(DISFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_FORM_ID using the alias name DisFormId.
     * @param value value to set the DIS_FORM_ID
     */
    public void setDisFormId(BigDecimal value) {
        setAttributeInternal(DISFORMID, value);
    }

    /**
     * Gets the attribute value for CONTI_RELATIONSHIP_TYPE using the alias name ContiRelationshipType.
     * @return the CONTI_RELATIONSHIP_TYPE
     */
    public String getContiRelationshipType() {
        return (String) getAttributeInternal(CONTIRELATIONSHIPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_RELATIONSHIP_TYPE using the alias name ContiRelationshipType.
     * @param value value to set the CONTI_RELATIONSHIP_TYPE
     */
    public void setContiRelationshipType(String value) {
        setAttributeInternal(CONTIRELATIONSHIPTYPE, value);
    }

    /**
     * Gets the attribute value for CONTI_FULL_NAME using the alias name ContiFullName.
     * @return the CONTI_FULL_NAME
     */
    public String getContiFullName() {
        return (String) getAttributeInternal(CONTIFULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_FULL_NAME using the alias name ContiFullName.
     * @param value value to set the CONTI_FULL_NAME
     */
    public void setContiFullName(String value) {
        setAttributeInternal(CONTIFULLNAME, value);
    }

    /**
     * Gets the attribute value for CONTI_PROPORTION using the alias name ContiProportion.
     * @return the CONTI_PROPORTION
     */
    public BigDecimal getContiProportion() {
        return (BigDecimal) getAttributeInternal(CONTIPROPORTION);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_PROPORTION using the alias name ContiProportion.
     * @param value value to set the CONTI_PROPORTION
     */
    public void setContiProportion(BigDecimal value) {
        setAttributeInternal(CONTIPROPORTION, value);
    }

    /**
     * Gets the attribute value for CONTI_PRIMARY_CONTACT_FLAG using the alias name ContiPrimaryContactFlag.
     * @return the CONTI_PRIMARY_CONTACT_FLAG
     */
    public String getContiPrimaryContactFlag() {
        return (String) getAttributeInternal(CONTIPRIMARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_PRIMARY_CONTACT_FLAG using the alias name ContiPrimaryContactFlag.
     * @param value value to set the CONTI_PRIMARY_CONTACT_FLAG
     */
    public void setContiPrimaryContactFlag(String value) {
        setAttributeInternal(CONTIPRIMARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for CONTI_SECONDARY_CONTACT_FLAG using the alias name ContiSecondaryContactFlag.
     * @return the CONTI_SECONDARY_CONTACT_FLAG
     */
    public String getContiSecondaryContactFlag() {
        return (String) getAttributeInternal(CONTISECONDARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_SECONDARY_CONTACT_FLAG using the alias name ContiSecondaryContactFlag.
     * @param value value to set the CONTI_SECONDARY_CONTACT_FLAG
     */
    public void setContiSecondaryContactFlag(String value) {
        setAttributeInternal(CONTISECONDARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for CONTI_COMMENTS using the alias name ContiComments.
     * @return the CONTI_COMMENTS
     */
    public String getContiComments() {
        return (String) getAttributeInternal(CONTICOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_COMMENTS using the alias name ContiComments.
     * @param value value to set the CONTI_COMMENTS
     */
    public void setContiComments(String value) {
        setAttributeInternal(CONTICOMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for REFERENCE1 using the alias name Reference1.
     * @return the REFERENCE1
     */
    public String getReference1() {
        return (String) getAttributeInternal(REFERENCE1);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE1 using the alias name Reference1.
     * @param value value to set the REFERENCE1
     */
    public void setReference1(String value) {
        setAttributeInternal(REFERENCE1, value);
    }

    /**
     * Gets the attribute value for CONTI_MOBILE_NO using the alias name ContiMobileNo.
     * @return the CONTI_MOBILE_NO
     */
    public String getContiMobileNo() {
        return (String) getAttributeInternal(CONTIMOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_MOBILE_NO using the alias name ContiMobileNo.
     * @param value value to set the CONTI_MOBILE_NO
     */
    public void setContiMobileNo(String value) {
        setAttributeInternal(CONTIMOBILENO, value);
    }

    /**
     * Gets the attribute value for CONTI_MOBILE_NO1 using the alias name ContiMobileNo1.
     * @return the CONTI_MOBILE_NO1
     */
    public String getContiMobileNo1() {
        return (String) getAttributeInternal(CONTIMOBILENO1);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_MOBILE_NO1 using the alias name ContiMobileNo1.
     * @param value value to set the CONTI_MOBILE_NO1
     */
    public void setContiMobileNo1(String value) {
        setAttributeInternal(CONTIMOBILENO1, value);
    }

    /**
     * Gets the attribute value for CONTI_RESI_ADDRESS using the alias name ContiResiAddress.
     * @return the CONTI_RESI_ADDRESS
     */
    public String getContiResiAddress() {
        return (String) getAttributeInternal(CONTIRESIADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_RESI_ADDRESS using the alias name ContiResiAddress.
     * @param value value to set the CONTI_RESI_ADDRESS
     */
    public void setContiResiAddress(String value) {
        setAttributeInternal(CONTIRESIADDRESS, value);
    }

    /**
     * Gets the attribute value for CONTI_EMAIL_ADDRESS using the alias name ContiEmailAddress.
     * @return the CONTI_EMAIL_ADDRESS
     */
    public String getContiEmailAddress() {
        return (String) getAttributeInternal(CONTIEMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_EMAIL_ADDRESS using the alias name ContiEmailAddress.
     * @param value value to set the CONTI_EMAIL_ADDRESS
     */
    public void setContiEmailAddress(String value) {
        setAttributeInternal(CONTIEMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for CONTI_DOB using the alias name ContiDob.
     * @return the CONTI_DOB
     */
    public Timestamp getContiDob() {
        return (Timestamp) getAttributeInternal(CONTIDOB);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_DOB using the alias name ContiDob.
     * @param value value to set the CONTI_DOB
     */
    public void setContiDob(Timestamp value) {
        setAttributeInternal(CONTIDOB, value);
    }

    /**
     * Gets the attribute value for CONTI_BENE_FLAG using the alias name ContiBeneFlag.
     * @return the CONTI_BENE_FLAG
     */
    public String getContiBeneFlag() {
        return (String) getAttributeInternal(CONTIBENEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTI_BENE_FLAG using the alias name ContiBeneFlag.
     * @param value value to set the CONTI_BENE_FLAG
     */
    public void setContiBeneFlag(String value) {
        setAttributeInternal(CONTIBENEFLAG, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Relationship_ROVO.
     */
    public RowSet getRelationship_ROVO() {
        return (RowSet) getAttributeInternal(RELATIONSHIP_ROVO);
    }
}

