package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 22 18:04:21 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSSHR_DIS_FORM_LINES_VORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXSSHR_DIS_FORM_LINES_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Comments,
        CreatedBy,
        CreationDate,
        DisFormId,
        DisFormLineId,
        FullName,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PrimaryContactFlag,
        Proportion,
        Reference1,
        RelationshipType,
        SecondaryContactFlag,
        MobileNo,
        EmerFullName,
        EmerMobileNo,
        EmerPrimaryContactFlag,
        EmerRelationshipType,
        EmerSecondaryContactFlag,
        MobileNo1,
        EmailAddress,
        ResiAddress,
        Dob,
        DisBeneFlag,
        Relationship_ROVO,
        E_Relationship_ROVO;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DISFORMID = AttributesEnum.DisFormId.index();
    public static final int DISFORMLINEID = AttributesEnum.DisFormLineId.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PRIMARYCONTACTFLAG = AttributesEnum.PrimaryContactFlag.index();
    public static final int PROPORTION = AttributesEnum.Proportion.index();
    public static final int REFERENCE1 = AttributesEnum.Reference1.index();
    public static final int RELATIONSHIPTYPE = AttributesEnum.RelationshipType.index();
    public static final int SECONDARYCONTACTFLAG = AttributesEnum.SecondaryContactFlag.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int EMERFULLNAME = AttributesEnum.EmerFullName.index();
    public static final int EMERMOBILENO = AttributesEnum.EmerMobileNo.index();
    public static final int EMERPRIMARYCONTACTFLAG = AttributesEnum.EmerPrimaryContactFlag.index();
    public static final int EMERRELATIONSHIPTYPE = AttributesEnum.EmerRelationshipType.index();
    public static final int EMERSECONDARYCONTACTFLAG = AttributesEnum.EmerSecondaryContactFlag.index();
    public static final int MOBILENO1 = AttributesEnum.MobileNo1.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int RESIADDRESS = AttributesEnum.ResiAddress.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int DISBENEFLAG = AttributesEnum.DisBeneFlag.index();
    public static final int RELATIONSHIP_ROVO = AttributesEnum.Relationship_ROVO.index();
    public static final int E_RELATIONSHIP_ROVO = AttributesEnum.E_Relationship_ROVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XXSSHR_DIS_FORM_LINES_VORowImpl() {
    }

    /**
     * Gets XXSSHR_DIS_FORM_LINES_EO entity object.
     * @return the XXSSHR_DIS_FORM_LINES_EO
     */
    public EntityImpl getXXSSHR_DIS_FORM_LINES_EO() {
        return (EntityImpl) getEntity(ENTITY_XXSSHR_DIS_FORM_LINES_EO);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for DIS_FORM_ID using the alias name DisFormId.
     * @return the DIS_FORM_ID
     */
    public BigDecimal getDisFormId() {
        return (BigDecimal) getAttributeInternal(DISFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_FORM_ID using the alias name DisFormId.
     * @param value value to set the DIS_FORM_ID
     */
    public void setDisFormId(BigDecimal value) {
        setAttributeInternal(DISFORMID, value);
    }

    /**
     * Gets the attribute value for DIS_FORM_LINE_ID using the alias name DisFormLineId.
     * @return the DIS_FORM_LINE_ID
     */
    public BigDecimal getDisFormLineId() {
        return (BigDecimal) getAttributeInternal(DISFORMLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_FORM_LINE_ID using the alias name DisFormLineId.
     * @param value value to set the DIS_FORM_LINE_ID
     */
    public void setDisFormLineId(BigDecimal value) {
        setAttributeInternal(DISFORMLINEID, value);
    }

    /**
     * Gets the attribute value for FULL_NAME using the alias name FullName.
     * @return the FULL_NAME
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FULL_NAME using the alias name FullName.
     * @param value value to set the FULL_NAME
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PRIMARY_CONTACT_FLAG using the alias name PrimaryContactFlag.
     * @return the PRIMARY_CONTACT_FLAG
     */
    public String getPrimaryContactFlag() {
        return (String) getAttributeInternal(PRIMARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIMARY_CONTACT_FLAG using the alias name PrimaryContactFlag.
     * @param value value to set the PRIMARY_CONTACT_FLAG
     */
    public void setPrimaryContactFlag(String value) {
        setAttributeInternal(PRIMARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for PROPORTION using the alias name Proportion.
     * @return the PROPORTION
     */
    public BigDecimal getProportion() {
        return (BigDecimal) getAttributeInternal(PROPORTION);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPORTION using the alias name Proportion.
     * @param value value to set the PROPORTION
     */
    public void setProportion(BigDecimal value) {
        setAttributeInternal(PROPORTION, value);
    }

    /**
     * Gets the attribute value for REFERENCE1 using the alias name Reference1.
     * @return the REFERENCE1
     */
    public String getReference1() {
        return (String) getAttributeInternal(REFERENCE1);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE1 using the alias name Reference1.
     * @param value value to set the REFERENCE1
     */
    public void setReference1(String value) {
        setAttributeInternal(REFERENCE1, value);
    }

    /**
     * Gets the attribute value for RELATIONSHIP_TYPE using the alias name RelationshipType.
     * @return the RELATIONSHIP_TYPE
     */
    public String getRelationshipType() {
        return (String) getAttributeInternal(RELATIONSHIPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RELATIONSHIP_TYPE using the alias name RelationshipType.
     * @param value value to set the RELATIONSHIP_TYPE
     */
    public void setRelationshipType(String value) {
        setAttributeInternal(RELATIONSHIPTYPE, value);
    }

    /**
     * Gets the attribute value for SECONDARY_CONTACT_FLAG using the alias name SecondaryContactFlag.
     * @return the SECONDARY_CONTACT_FLAG
     */
    public String getSecondaryContactFlag() {
        return (String) getAttributeInternal(SECONDARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for SECONDARY_CONTACT_FLAG using the alias name SecondaryContactFlag.
     * @param value value to set the SECONDARY_CONTACT_FLAG
     */
    public void setSecondaryContactFlag(String value) {
        setAttributeInternal(SECONDARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for MOBILE_NO using the alias name MobileNo.
     * @return the MOBILE_NO
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_NO using the alias name MobileNo.
     * @param value value to set the MOBILE_NO
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for EMER_FULL_NAME using the alias name EmerFullName.
     * @return the EMER_FULL_NAME
     */
    public String getEmerFullName() {
        return (String) getAttributeInternal(EMERFULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMER_FULL_NAME using the alias name EmerFullName.
     * @param value value to set the EMER_FULL_NAME
     */
    public void setEmerFullName(String value) {
        setAttributeInternal(EMERFULLNAME, value);
    }

    /**
     * Gets the attribute value for EMER_MOBILE_NO using the alias name EmerMobileNo.
     * @return the EMER_MOBILE_NO
     */
    public String getEmerMobileNo() {
        return (String) getAttributeInternal(EMERMOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMER_MOBILE_NO using the alias name EmerMobileNo.
     * @param value value to set the EMER_MOBILE_NO
     */
    public void setEmerMobileNo(String value) {
        setAttributeInternal(EMERMOBILENO, value);
    }

    /**
     * Gets the attribute value for EMER_PRIMARY_CONTACT_FLAG using the alias name EmerPrimaryContactFlag.
     * @return the EMER_PRIMARY_CONTACT_FLAG
     */
    public String getEmerPrimaryContactFlag() {
        return (String) getAttributeInternal(EMERPRIMARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for EMER_PRIMARY_CONTACT_FLAG using the alias name EmerPrimaryContactFlag.
     * @param value value to set the EMER_PRIMARY_CONTACT_FLAG
     */
    public void setEmerPrimaryContactFlag(String value) {
        setAttributeInternal(EMERPRIMARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for EMER_RELATIONSHIP_TYPE using the alias name EmerRelationshipType.
     * @return the EMER_RELATIONSHIP_TYPE
     */
    public String getEmerRelationshipType() {
        return (String) getAttributeInternal(EMERRELATIONSHIPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMER_RELATIONSHIP_TYPE using the alias name EmerRelationshipType.
     * @param value value to set the EMER_RELATIONSHIP_TYPE
     */
    public void setEmerRelationshipType(String value) {
        setAttributeInternal(EMERRELATIONSHIPTYPE, value);
    }

    /**
     * Gets the attribute value for EMER_SECONDARY_CONTACT_FLAG using the alias name EmerSecondaryContactFlag.
     * @return the EMER_SECONDARY_CONTACT_FLAG
     */
    public String getEmerSecondaryContactFlag() {
        return (String) getAttributeInternal(EMERSECONDARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for EMER_SECONDARY_CONTACT_FLAG using the alias name EmerSecondaryContactFlag.
     * @param value value to set the EMER_SECONDARY_CONTACT_FLAG
     */
    public void setEmerSecondaryContactFlag(String value) {
        setAttributeInternal(EMERSECONDARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for MOBILE_NO1 using the alias name MobileNo1.
     * @return the MOBILE_NO1
     */
    public String getMobileNo1() {
        return (String) getAttributeInternal(MOBILENO1);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_NO1 using the alias name MobileNo1.
     * @param value value to set the MOBILE_NO1
     */
    public void setMobileNo1(String value) {
        setAttributeInternal(MOBILENO1, value);
    }

    /**
     * Gets the attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @return the EMAIL_ADDRESS
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @param value value to set the EMAIL_ADDRESS
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for RESI_ADDRESS using the alias name ResiAddress.
     * @return the RESI_ADDRESS
     */
    public String getResiAddress() {
        return (String) getAttributeInternal(RESIADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for RESI_ADDRESS using the alias name ResiAddress.
     * @param value value to set the RESI_ADDRESS
     */
    public void setResiAddress(String value) {
        setAttributeInternal(RESIADDRESS, value);
    }

    /**
     * Gets the attribute value for DOB using the alias name Dob.
     * @return the DOB
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as attribute value for DOB using the alias name Dob.
     * @param value value to set the DOB
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for DIS_BENE_FLAG using the alias name DisBeneFlag.
     * @return the DIS_BENE_FLAG
     */
    public String getDisBeneFlag() {
        return (String) getAttributeInternal(DISBENEFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_BENE_FLAG using the alias name DisBeneFlag.
     * @param value value to set the DIS_BENE_FLAG
     */
    public void setDisBeneFlag(String value) {
        setAttributeInternal(DISBENEFLAG, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Relationship_ROVO.
     */
    public RowSet getRelationship_ROVO() {
        return (RowSet) getAttributeInternal(RELATIONSHIP_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> E_Relationship_ROVO.
     */
    public RowSet getE_Relationship_ROVO() {
        return (RowSet) getAttributeInternal(E_RELATIONSHIP_ROVO);
    }
}

