package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 22 18:04:24 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSSHR_DIS_FORM_LINES_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XXSSHR_DIS_FORM_LINES_VOImpl() {
    }
}

