package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 13 20:29:26 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxsshrDisContingentLinesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DisContingentId,
        DisFormId,
        ContiRelationshipType,
        ContiFullName,
        ContiProportion,
        ContiPrimaryContactFlag,
        ContiSecondaryContactFlag,
        ContiComments,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        Reference1,
        ContiMobileNo,
        ContiMobileNo1,
        ContiResiAddress,
        ContiEmailAddress,
        ContiDob,
        ContiBeneFlag,
        XXSSHR_DIS_FORM_Hdr_EO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DISCONTINGENTID = AttributesEnum.DisContingentId.index();
    public static final int DISFORMID = AttributesEnum.DisFormId.index();
    public static final int CONTIRELATIONSHIPTYPE = AttributesEnum.ContiRelationshipType.index();
    public static final int CONTIFULLNAME = AttributesEnum.ContiFullName.index();
    public static final int CONTIPROPORTION = AttributesEnum.ContiProportion.index();
    public static final int CONTIPRIMARYCONTACTFLAG = AttributesEnum.ContiPrimaryContactFlag.index();
    public static final int CONTISECONDARYCONTACTFLAG = AttributesEnum.ContiSecondaryContactFlag.index();
    public static final int CONTICOMMENTS = AttributesEnum.ContiComments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int REFERENCE1 = AttributesEnum.Reference1.index();
    public static final int CONTIMOBILENO = AttributesEnum.ContiMobileNo.index();
    public static final int CONTIMOBILENO1 = AttributesEnum.ContiMobileNo1.index();
    public static final int CONTIRESIADDRESS = AttributesEnum.ContiResiAddress.index();
    public static final int CONTIEMAILADDRESS = AttributesEnum.ContiEmailAddress.index();
    public static final int CONTIDOB = AttributesEnum.ContiDob.index();
    public static final int CONTIBENEFLAG = AttributesEnum.ContiBeneFlag.index();
    public static final int XXSSHR_DIS_FORM_HDR_EO = AttributesEnum.XXSSHR_DIS_FORM_Hdr_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxsshrDisContingentLinesEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.XxsshrDisContingentLinesEO");
    }


    /**
     * Gets the attribute value for DisContingentId, using the alias name DisContingentId.
     * @return the value of DisContingentId
     */
    public BigDecimal getDisContingentId() {
        return (BigDecimal) getAttributeInternal(DISCONTINGENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisContingentId.
     * @param value value to set the DisContingentId
     */
    public void setDisContingentId(BigDecimal value) {
        setAttributeInternal(DISCONTINGENTID, value);
    }

    /**
     * Gets the attribute value for DisFormId, using the alias name DisFormId.
     * @return the value of DisFormId
     */
    public BigDecimal getDisFormId() {
        return (BigDecimal) getAttributeInternal(DISFORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisFormId.
     * @param value value to set the DisFormId
     */
    public void setDisFormId(BigDecimal value) {
        setAttributeInternal(DISFORMID, value);
    }

    /**
     * Gets the attribute value for ContiRelationshipType, using the alias name ContiRelationshipType.
     * @return the value of ContiRelationshipType
     */
    public String getContiRelationshipType() {
        return (String) getAttributeInternal(CONTIRELATIONSHIPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiRelationshipType.
     * @param value value to set the ContiRelationshipType
     */
    public void setContiRelationshipType(String value) {
        setAttributeInternal(CONTIRELATIONSHIPTYPE, value);
    }

    /**
     * Gets the attribute value for ContiFullName, using the alias name ContiFullName.
     * @return the value of ContiFullName
     */
    public String getContiFullName() {
        return (String) getAttributeInternal(CONTIFULLNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiFullName.
     * @param value value to set the ContiFullName
     */
    public void setContiFullName(String value) {
        setAttributeInternal(CONTIFULLNAME, value);
    }

    /**
     * Gets the attribute value for ContiProportion, using the alias name ContiProportion.
     * @return the value of ContiProportion
     */
    public BigDecimal getContiProportion() {
        return (BigDecimal) getAttributeInternal(CONTIPROPORTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiProportion.
     * @param value value to set the ContiProportion
     */
    public void setContiProportion(BigDecimal value) {
        setAttributeInternal(CONTIPROPORTION, value);
    }

    /**
     * Gets the attribute value for ContiPrimaryContactFlag, using the alias name ContiPrimaryContactFlag.
     * @return the value of ContiPrimaryContactFlag
     */
    public String getContiPrimaryContactFlag() {
        return (String) getAttributeInternal(CONTIPRIMARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiPrimaryContactFlag.
     * @param value value to set the ContiPrimaryContactFlag
     */
    public void setContiPrimaryContactFlag(String value) {
        setAttributeInternal(CONTIPRIMARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for ContiSecondaryContactFlag, using the alias name ContiSecondaryContactFlag.
     * @return the value of ContiSecondaryContactFlag
     */
    public String getContiSecondaryContactFlag() {
        return (String) getAttributeInternal(CONTISECONDARYCONTACTFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiSecondaryContactFlag.
     * @param value value to set the ContiSecondaryContactFlag
     */
    public void setContiSecondaryContactFlag(String value) {
        setAttributeInternal(CONTISECONDARYCONTACTFLAG, value);
    }

    /**
     * Gets the attribute value for ContiComments, using the alias name ContiComments.
     * @return the value of ContiComments
     */
    public String getContiComments() {
        return (String) getAttributeInternal(CONTICOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiComments.
     * @param value value to set the ContiComments
     */
    public void setContiComments(String value) {
        setAttributeInternal(CONTICOMMENTS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Reference1, using the alias name Reference1.
     * @return the value of Reference1
     */
    public String getReference1() {
        return (String) getAttributeInternal(REFERENCE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Reference1.
     * @param value value to set the Reference1
     */
    public void setReference1(String value) {
        setAttributeInternal(REFERENCE1, value);
    }

    /**
     * Gets the attribute value for ContiMobileNo, using the alias name ContiMobileNo.
     * @return the value of ContiMobileNo
     */
    public String getContiMobileNo() {
        return (String) getAttributeInternal(CONTIMOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiMobileNo.
     * @param value value to set the ContiMobileNo
     */
    public void setContiMobileNo(String value) {
        setAttributeInternal(CONTIMOBILENO, value);
    }

    /**
     * Gets the attribute value for ContiMobileNo1, using the alias name ContiMobileNo1.
     * @return the value of ContiMobileNo1
     */
    public String getContiMobileNo1() {
        return (String) getAttributeInternal(CONTIMOBILENO1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiMobileNo1.
     * @param value value to set the ContiMobileNo1
     */
    public void setContiMobileNo1(String value) {
        setAttributeInternal(CONTIMOBILENO1, value);
    }

    /**
     * Gets the attribute value for ContiResiAddress, using the alias name ContiResiAddress.
     * @return the value of ContiResiAddress
     */
    public String getContiResiAddress() {
        return (String) getAttributeInternal(CONTIRESIADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiResiAddress.
     * @param value value to set the ContiResiAddress
     */
    public void setContiResiAddress(String value) {
        setAttributeInternal(CONTIRESIADDRESS, value);
    }

    /**
     * Gets the attribute value for ContiEmailAddress, using the alias name ContiEmailAddress.
     * @return the value of ContiEmailAddress
     */
    public String getContiEmailAddress() {
        return (String) getAttributeInternal(CONTIEMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiEmailAddress.
     * @param value value to set the ContiEmailAddress
     */
    public void setContiEmailAddress(String value) {
        setAttributeInternal(CONTIEMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for ContiDob, using the alias name ContiDob.
     * @return the value of ContiDob
     */
    public Timestamp getContiDob() {
        return (Timestamp) getAttributeInternal(CONTIDOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiDob.
     * @param value value to set the ContiDob
     */
    public void setContiDob(Timestamp value) {
        setAttributeInternal(CONTIDOB, value);
    }

    /**
     * Gets the attribute value for ContiBeneFlag, using the alias name ContiBeneFlag.
     * @return the value of ContiBeneFlag
     */
    public String getContiBeneFlag() {
        return (String) getAttributeInternal(CONTIBENEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContiBeneFlag.
     * @param value value to set the ContiBeneFlag
     */
    public void setContiBeneFlag(String value) {
        setAttributeInternal(CONTIBENEFLAG, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getXXSSHR_DIS_FORM_Hdr_EO() {
        return (EntityImpl) getAttributeInternal(XXSSHR_DIS_FORM_HDR_EO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setXXSSHR_DIS_FORM_Hdr_EO(EntityImpl value) {
        setAttributeInternal(XXSSHR_DIS_FORM_HDR_EO, value);
    }

    /**
     * @param disContingentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal disContingentId) {
        return new Key(new Object[] { disContingentId });
    }


}

