package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 14 15:43:22 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XXSSHR_DIS_FORM_Hdr_VORowImpl extends ViewRowImpl {
    public static final int ENTITY_XXSSHR_DIS_FORM_HDR_EO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ApprovalStatus,
        ApproverComments,
        BusinessUnitId,
        Comments,
        CreatedBy,
        CreationDate,
        DisFormId,
        DisFormNo,
        ErrorMsg,
        LastUpdateDate,
        LastUpdateLogin,
        LastUpdatedBy,
        PayrollBatchName,
        PersonId,
        SoaFlowid,
        TotalProportion,
        TransactionDate,
        DisConfirmFlag,
        DisUnderstandFlag,
        TotalContiProportion,
        Name_Trans,
        Number_Trans,
        Email_Trans,
        Group_Trans,
        Trans_Cadre,
        XXSSHR_DIS_FORM_LINES_VO,
        XXSSHR_DIS_EMERGENCY_DETAILS_VO,
        XxsshrDisContingentLinesVO,
        Employee_View_ROVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int DISFORMID = AttributesEnum.DisFormId.index();
    public static final int DISFORMNO = AttributesEnum.DisFormNo.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int TOTALPROPORTION = AttributesEnum.TotalProportion.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int DISCONFIRMFLAG = AttributesEnum.DisConfirmFlag.index();
    public static final int DISUNDERSTANDFLAG = AttributesEnum.DisUnderstandFlag.index();
    public static final int TOTALCONTIPROPORTION = AttributesEnum.TotalContiProportion.index();
    public static final int NAME_TRANS = AttributesEnum.Name_Trans.index();
    public static final int NUMBER_TRANS = AttributesEnum.Number_Trans.index();
    public static final int EMAIL_TRANS = AttributesEnum.Email_Trans.index();
    public static final int GROUP_TRANS = AttributesEnum.Group_Trans.index();
    public static final int TRANS_CADRE = AttributesEnum.Trans_Cadre.index();
    public static final int XXSSHR_DIS_FORM_LINES_VO = AttributesEnum.XXSSHR_DIS_FORM_LINES_VO.index();
    public static final int XXSSHR_DIS_EMERGENCY_DETAILS_VO = AttributesEnum.XXSSHR_DIS_EMERGENCY_DETAILS_VO.index();
    public static final int XXSSHRDISCONTINGENTLINESVO = AttributesEnum.XxsshrDisContingentLinesVO.index();
    public static final int EMPLOYEE_VIEW_ROVO1 = AttributesEnum.Employee_View_ROVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XXSSHR_DIS_FORM_Hdr_VORowImpl() {
    }

    /**
     * Gets XXSSHR_DIS_FORM_Hdr_EO entity object.
     * @return the XXSSHR_DIS_FORM_Hdr_EO
     */
    public EntityImpl getXXSSHR_DIS_FORM_Hdr_EO() {
        return (EntityImpl) getEntity(ENTITY_XXSSHR_DIS_FORM_HDR_EO);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for DIS_FORM_ID using the alias name DisFormId.
     * @return the DIS_FORM_ID
     */
    public BigDecimal getDisFormId() {
        return (BigDecimal) getAttributeInternal(DISFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_FORM_ID using the alias name DisFormId.
     * @param value value to set the DIS_FORM_ID
     */
    public void setDisFormId(BigDecimal value) {
        setAttributeInternal(DISFORMID, value);
    }

    /**
     * Gets the attribute value for DIS_FORM_NO using the alias name DisFormNo.
     * @return the DIS_FORM_NO
     */
    public String getDisFormNo() {
        return (String) getAttributeInternal(DISFORMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_FORM_NO using the alias name DisFormNo.
     * @param value value to set the DIS_FORM_NO
     */
    public void setDisFormNo(String value) {
        setAttributeInternal(DISFORMNO, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for TOTAL_PROPORTION using the alias name TotalProportion.
     * @return the TOTAL_PROPORTION
     */
    public BigDecimal getTotalProportion() {
        BigDecimal totVal = new BigDecimal(0);
        RowIterator rs = getXXSSHR_DIS_FORM_LINES_VO();
        while (rs.hasNext()) {
            Row r = rs.next();
            totVal =
                totVal.add(r.getAttribute("Proportion") == null ? new BigDecimal(0) :
                           (BigDecimal) r.getAttribute("Proportion"));
        }
        return totVal;
        // return (BigDecimal) getAttributeInternal(TOTALPROPORTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_PROPORTION using the alias name TotalProportion.
     * @param value value to set the TOTAL_PROPORTION
     */
    public void setTotalProportion(BigDecimal value) {
        setAttributeInternal(TOTALPROPORTION, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @return the TRANSACTION_DATE
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @param value value to set the TRANSACTION_DATE
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for DIS_CONFIRM_FLAG using the alias name DisConfirmFlag.
     * @return the DIS_CONFIRM_FLAG
     */
    public String getDisConfirmFlag() {
        return (String) getAttributeInternal(DISCONFIRMFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_CONFIRM_FLAG using the alias name DisConfirmFlag.
     * @param value value to set the DIS_CONFIRM_FLAG
     */
    public void setDisConfirmFlag(String value) {
        setAttributeInternal(DISCONFIRMFLAG, value);
    }

    /**
     * Gets the attribute value for DIS_UNDERSTAND_FLAG using the alias name DisUnderstandFlag.
     * @return the DIS_UNDERSTAND_FLAG
     */
    public String getDisUnderstandFlag() {
        return (String) getAttributeInternal(DISUNDERSTANDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DIS_UNDERSTAND_FLAG using the alias name DisUnderstandFlag.
     * @param value value to set the DIS_UNDERSTAND_FLAG
     */
    public void setDisUnderstandFlag(String value) {
        setAttributeInternal(DISUNDERSTANDFLAG, value);
    }

    /**
     * Gets the attribute value for TOTAL_CONTI_PROPORTION using the alias name TotalContiProportion.
     * @return the TOTAL_CONTI_PROPORTION
     */
    public BigDecimal getTotalContiProportion() {
        //return (BigDecimal) getAttributeInternal(TOTALCONTIPROPORTION);
        BigDecimal totContiVal = new BigDecimal(0);
        RowIterator rsItr = getXxsshrDisContingentLinesVO();
        while (rsItr.hasNext()) {
            Row row = rsItr.next();
            totContiVal =
                totContiVal.add(row.getAttribute("ContiProportion") == null ? new BigDecimal(0) :
                                (BigDecimal) row.getAttribute("ContiProportion"));
        }
        return totContiVal;
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_CONTI_PROPORTION using the alias name TotalContiProportion.
     * @param value value to set the TOTAL_CONTI_PROPORTION
     */
    public void setTotalContiProportion(BigDecimal value) {
        setAttributeInternal(TOTALCONTIPROPORTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name_Trans.
     * @return the Name_Trans
     */
    public String getName_Trans() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO1().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("DisplayName").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(NAME_TRANS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name_Trans.
     * @param value value to set the  Name_Trans
     */
    public void setName_Trans(String value) {
        setAttributeInternal(NAME_TRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Number_Trans.
     * @return the Number_Trans
     */
    public String getNumber_Trans() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO1().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PersonNumber").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(NUMBER_TRANS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Number_Trans.
     * @param value value to set the  Number_Trans
     */
    public void setNumber_Trans(String value) {
        setAttributeInternal(NUMBER_TRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email_Trans.
     * @return the Email_Trans
     */
    public String getEmail_Trans() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO1().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("EmailAddress").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(EMAIL_TRANS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email_Trans.
     * @param value value to set the  Email_Trans
     */
    public void setEmail_Trans(String value) {
        setAttributeInternal(EMAIL_TRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Group_Trans.
     * @return the Group_Trans
     */
    public String getGroup_Trans() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO1().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("BusinessUnitName").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(GROUP_TRANS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Group_Trans.
     * @param value value to set the  Group_Trans
     */
    public void setGroup_Trans(String value) {
        setAttributeInternal(GROUP_TRANS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_Cadre.
     * @return the Trans_Cadre
     */
    public String getTrans_Cadre() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO1().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("Cadre").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(TRANS_CADRE);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_Cadre.
     * @param value value to set the  Trans_Cadre
     */
    public void setTrans_Cadre(String value) {
        setAttributeInternal(TRANS_CADRE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XXSSHR_DIS_FORM_LINES_VO.
     */
    public RowIterator getXXSSHR_DIS_FORM_LINES_VO() {
        return (RowIterator) getAttributeInternal(XXSSHR_DIS_FORM_LINES_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XXSSHR_DIS_EMERGENCY_DETAILS_VO.
     */
    public RowIterator getXXSSHR_DIS_EMERGENCY_DETAILS_VO() {
        return (RowIterator) getAttributeInternal(XXSSHR_DIS_EMERGENCY_DETAILS_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxsshrDisContingentLinesVO.
     */
    public RowIterator getXxsshrDisContingentLinesVO() {
        return (RowIterator) getAttributeInternal(XXSSHRDISCONTINGENTLINESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO1.
     */
    public RowSet getEmployee_View_ROVO1() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO1);
    }
}

